name = "Entropyest"
uuid = "57c98347-1749-483d-a0a1-ae5e974f2dd2"
authors = ["Anand Ray <a2ray@ucsd.edu>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DensityRatioEstimation = "ab46fb84-d57c-11e9-2f65-6f72e4a7229f"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DistributedArrays = "aaf54ef3-cdf8-58ed-94cc-d582ad619b94"
HiQGA = "01574e87-63b6-4466-925a-334cf7e21b6b"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
